title: Sumitra Badrinathan
logo: /Assets/photo.jpg
description: Assistant Professor of Political Science at American University. Misinformation, media, and politics in South Asia.
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
